In [1]:
import pandas as pd 

bball_data=pd.read_csv('leagues_NBA_2015_totals_totals.csv',sep=';') 

print bball_data.shape
print bball_data.head()

(651, 30)
    Rk          Player Pos  Age   Tm   G  GS    MP   FG  FGA  ...     FT%  \
0  492    Tyler Zeller   C   25  BOS  82  59  1731  340  619  ...   0.823
1  491     Cody Zeller   C   22  CHO  62  45  1487  172  373  ...   0.774
2  490  Thaddeus Young  PF   26  TOT  76  68  2434  451  968  ...   0.655
3  490  Thaddeus Young  PF   26  MIN  48  48  1605  289  641  ...   0.682
4  490  Thaddeus Young  PF   26  BRK  28  20   829  162  327  ...   0.606

   ORB  DRB  TRB  AST  STL  BLK  TOV   PF   PTS
0  146  319  465  113   18   52   76  205   833
1   97  265  362  100   34   49   62  156   472
2  127  284  411  173  124   25  117  171  1071
3   75  170  245  135   86   17   75  115   685
4   52  114  166   38   38    8   42   56   386

[5 rows x 30 columns]

In [2]:
bball_data.describe()

,Rk,Age,G,GS,MP,FG,FGA,FG%,3P,3PA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
count,651.000000,651.000000,651.000000,651.000000,651.000000,651.000000,651.000000,649.000000,651.000000,651.000000,...,626.000000,651.000000,651.000000,651.000000,651.000000,651.000000,651.000000,651.000000,651.000000,651.000000
mean,256.520737,26.500768,45.960061,21.099846,1041.775730,160.778802,359.763441,0.427404,33.917051,97.419355,...,0.722800,46.414747,137.298003,183.712750,95.960061,33.367127,20.072197,59.511521,87.199693,428.067588
std,143.081604,4.110914,25.503151,25.932412,806.253103,148.971531,322.834979,0.100285,44.168306,118.003315,...,0.154606,56.505820,130.956177,181.471919,116.919926,31.720880,29.058392,55.845731,64.768084,401.564362
min,1.000000,19.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,130.500000,23.000000,24.000000,0.000000,272.000000,33.500000,80.500000,0.389000,1.000000,5.000000,...,0.650500,8.000000,31.000000,40.000000,15.000000,8.000000,2.000000,13.500000,26.000000,90.000000
50%,262.000000,26.000000,48.000000,9.000000,896.000000,120.000000,285.000000,0.426000,13.000000,43.000000,...,0.750000,27.000000,106.000000,138.000000,57.000000,26.000000,10.000000,46.000000,77.000000,308.000000
75%,381.500000,29.000000,70.000000,35.000000,1674.000000,251.000000,535.500000,0.472000,55.000000,165.000000,...,0.825000,61.500000,196.500000,262.000000,132.500000,48.000000,23.000000,90.500000,137.000000,658.000000
max,492.000000,38.000000,83.000000,82.000000,2981.000000,659.000000,1471.000000,1.000000,286.000000,646.000000,...,1.000000,437.000000,829.000000,1226.000000,838.000000,163.000000,200.000000,321.000000,285.000000,2217.000000

In [3]:
offense_makeup=bball_data[['FG','AST','FTA','3P']]
offense_makeuphead()

NameError: name 'offense_makeuphead' is not defined